### ISSUE TITLE
Add `tap_action`

### ISSUE THREAD

**Issue by dimmanramone** [hasl-platform/lovelace-hasl-departure-card#1]
Requested from @tomoqv 

> I want to bring up e.g. a pop-up card with more details when tapping the hasl-card.

**Comment by dimmanramone** [comment]
@tomoqv In the dev branch there is a new version with tap_action options. More than welcome to test it.  Otherwise you can wait until it makes the master branch.

**Comment by tomoqv** [comment]
Just tried to get tap_action to work, but I am unsure of the config when using `browser_mod.command`.
The config I use with other lovelace cards doesn't work, e.g.:
```
        tap_action:
          action: call-service
          service: browser_mod.command
          service_data:
            command: popup
            title: Avgångar
            card:
              !include /config/lovelace/single-cards/sl-details.yaml
            deviceID:
              - this
I realize the hasl solution is somewhat different, but what do I put in `domain, service `and `data`?

Thanks!
```

**Comment by dimmanramone** [comment]
@tomoqv I'll take a look in the weekend and get back to you

**Comment by tomoqv** [comment]
Thank you. Offset seems to work just fine btw.

**Comment by dimmanramone** [comment]
@tomoqv Can you test...

` tap_action:
          action: service
          service_config:
            domain: browser_mod
            service: command
            service_data:
              command: popup
              title: Avgångar
              card:
                !include /config/lovelace/single-cards/sl-details.yaml
              deviceID:
              - this`

**Comment by tomoqv** [comment]
Unfortunately I am not getting any traffic info at all right now. Log says this:
```
2019-11-22 16:46:34 ERROR (MainThread) [hacs] You have custom-cards/monster-card installed with HACS this repository has been blacklisted, please consider removing it.
2019-11-22 16:46:35 ERROR (MainThread) [hacs] You have custom-cards/monster-card installed with HACS this repository has been blacklisted, please consider removing it.
```

Which is strange, because I am on the Silver level on my Real Time Info API...

**Comment by tomoqv** [comment]
Phew, it's back again after another restart. Still the same error as above, though.

**Comment by tomoqv** [comment]
`tap_action` with your suggested config doesn't work. The card is not recognized as "tappable".

**Comment by dimmanramone** [comment]
@tomoqv I don't have any experience in browser_mod, I actually just installed it and I didn't have any trouble in configuring the tap_action service with browser_mod.

My configurations is the following.
```
tap_action: service
    service_config:
      domain: browser_mod
      service: popup
      data:
        title: Testing
        card:
          !include home02.yaml
```

**Comment by tomoqv** [comment]
Sorry for the delay, haven't had time to look at this until now.
I get a Lovelace error with the configuration above. I tried instead:
```
        tap_action:
          action: call-service
          service_config:
            domain: browser_mod
            service: popup
            data:
              title: Avgångar
              card:
                !include /config/lovelace/single-cards/sl-details.yaml
              deviceID:
                - this

```
It doesn't give an error, but doesn't make the card clickable either.

**Comment by dimmanramone** [comment]
@tomoqv There is no **tap_action: call-service** or **action attribute** for tap_action.

As is stated in the documentation it is **tap_action: service** or **info**

It works fine with the example in my previous comment. Can you send me the lovelace error you get?

**Comment by tomoqv** [comment]
`while parsing a block mapping in "/config/lovelace/lovelace-main-view-tablet.yaml", line 140, column 9 expected <block end>, but found '<block mapping start>' in "/config/lovelace/lovelace-main-view-tablet.yaml", line 168, column 11`

**Comment by tomoqv** [comment]
And just to make sure, latest version of the card is 19-11-22, right?

**Comment by dimmanramone** [comment]
@dimmanramone this is the last version of the card https://github.com/hasl-platform/lovelace-hasl-departure-card/releases/tag/v2.4.0

It would help a little bit more if you post your lovelace view lovelace-main-view-tablet.yaml

**Comment by tomoqv** [comment]
I guess this part will do:
```
    - type: horizontal-stack
      cards:
      - type: "custom:hasl-departure-card"
        show_cardname: false
        header: false
        departures: true
        timeleft: false
        updated: false
        offset: 5
        hide_departed: true
        language: sv-SE
        entities:
          - sensor.mossens_ip
          - sensor.alleparken
        style: |
          ha-card {
            font-size: 1.2em;
          }
        tap_action: service
          service_config:
            domain: browser_mod
            service: popup
            data:
              title: Avgångar
              card:
                !include /config/lovelace/single-cards/sl-details.yaml
              deviceID:
                - this

```

**Comment by dimmanramone** [comment]
@tomoqv Is the the service_config line, line 140?

**Comment by tomoqv** [comment]
No, line 140 is:
`      - type: "custom:hasl-departure-card"`

**Comment by dimmanramone** [comment]
@tomoqv I think that the problem in service_config, you have an extra indentation from there and the following lines.

```
- type: horizontal-stack
  cards:
  - type: "custom:hasl-departure-card"
    show_cardname: false
    header: false
    departures: true
    timeleft: false
    updated: false
    offset: 5
    hide_departed: true
    language: sv-SE
    entities:
      - sensor.mossens_ip
      - sensor.alleparken
    style: |
      ha-card {
        font-size: 1.2em;
      }
    tap_action: service
    service_config:
      domain: browser_mod
      service: popup
      data:
        title: Avgångar
        card:
          !include /config/lovelace/single-cards/sl-details.yaml
        deviceID:
          - this
```

**Comment by tomoqv** [comment]
Looking in my text editor, there is a 2-space indentation of `service_config` in relation to `tap_action`. Is that what you mean?

**Comment by dimmanramone** [comment]
@tomoqv Yes.

**Comment by tomoqv** [comment]
Ok, removing that I get:
`Failed to call service browser_mod/popup. Service not found.` popping up in the Lovelace UI.

**Comment by dimmanramone** [comment]
@tomoqv One step closer :) Strange though if you have installed browser mod you shouldn't get this.
But that's not the hasl card error anymore.

**Comment by tomoqv** [comment]
I know, all my other browser_mod.popup work. hasl card has a different implementation of tap_action though.

**Comment by tomoqv** [comment]
As an example, this works fine:
```
      - type: vertical-stack
        cards:
        - type: custom:button-card
          name: God natt...
          entity: light.evening_lights
          entity_picture: /local/emojis/sleepy.png
          show_entity_picture: true
          aspect_ratio: 2/1
          size: 30%
          tap_action:
            action: call-service
            service: browser_mod.command
            service_data:
              command: popup
              title: Godnatt
              card:
                !include /config/lovelace/single-cards/lights-out-night.yaml
              deviceID:
                - this

```
